# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import blog_post_pb2 as blog__post__pb2


class BlogPosterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePost = channel.unary_unary(
                '/BlogPoster/CreatePost',
                request_serializer=blog__post__pb2.CreateBlogPost.SerializeToString,
                response_deserializer=blog__post__pb2.BlogPost.FromString,
                )
        self.GetPost = channel.unary_unary(
                '/BlogPoster/GetPost',
                request_serializer=blog__post__pb2.GetPostRequest.SerializeToString,
                response_deserializer=blog__post__pb2.BlogPost.FromString,
                )
        self.GetAllPost = channel.unary_unary(
                '/BlogPoster/GetAllPost',
                request_serializer=blog__post__pb2.GetAllPostRequest.SerializeToString,
                response_deserializer=blog__post__pb2.GetAllPostResponse.FromString,
                )


class BlogPosterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePost(self, request, context):
        """Creates a blog post
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlogPosterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=blog__post__pb2.CreateBlogPost.FromString,
                    response_serializer=blog__post__pb2.BlogPost.SerializeToString,
            ),
            'GetPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPost,
                    request_deserializer=blog__post__pb2.GetPostRequest.FromString,
                    response_serializer=blog__post__pb2.BlogPost.SerializeToString,
            ),
            'GetAllPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllPost,
                    request_deserializer=blog__post__pb2.GetAllPostRequest.FromString,
                    response_serializer=blog__post__pb2.GetAllPostResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BlogPoster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BlogPoster(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BlogPoster/CreatePost',
            blog__post__pb2.CreateBlogPost.SerializeToString,
            blog__post__pb2.BlogPost.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BlogPoster/GetPost',
            blog__post__pb2.GetPostRequest.SerializeToString,
            blog__post__pb2.BlogPost.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BlogPoster/GetAllPost',
            blog__post__pb2.GetAllPostRequest.SerializeToString,
            blog__post__pb2.GetAllPostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
