# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blog_post.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blog_post.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x62log_post.proto\"G\n\x08\x42logPost\x12\x0b\n\x03id_\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x11\n\tpublished\x18\x04 \x01(\x08\"@\n\x0e\x43reateBlogPost\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x11\n\tpublished\x18\x04 \x01(\x08\"\x1d\n\x0eGetPostRequest\x12\x0b\n\x03id_\x18\x01 \x01(\x05\"3\n\x11GetAllPostRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08per_page\x18\x02 \x01(\x05\"P\n\x12GetAllPostResponse\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08per_page\x18\x02 \x01(\x05\x12\x1a\n\x07records\x18\x03 \x03(\x0b\x32\t.BlogPost2\x9a\x01\n\nBlogPoster\x12*\n\nCreatePost\x12\x0f.CreateBlogPost\x1a\t.BlogPost\"\x00\x12\'\n\x07GetPost\x12\x0f.GetPostRequest\x1a\t.BlogPost\"\x00\x12\x37\n\nGetAllPost\x12\x12.GetAllPostRequest\x1a\x13.GetAllPostResponse\"\x00\x62\x06proto3'
)




_BLOGPOST = _descriptor.Descriptor(
  name='BlogPost',
  full_name='BlogPost',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_', full_name='BlogPost.id_', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='BlogPost.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='BlogPost.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='published', full_name='BlogPost.published', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=90,
)


_CREATEBLOGPOST = _descriptor.Descriptor(
  name='CreateBlogPost',
  full_name='CreateBlogPost',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='CreateBlogPost.title', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='CreateBlogPost.text', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='published', full_name='CreateBlogPost.published', index=2,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=156,
)


_GETPOSTREQUEST = _descriptor.Descriptor(
  name='GetPostRequest',
  full_name='GetPostRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_', full_name='GetPostRequest.id_', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=187,
)


_GETALLPOSTREQUEST = _descriptor.Descriptor(
  name='GetAllPostRequest',
  full_name='GetAllPostRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='GetAllPostRequest.page', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='per_page', full_name='GetAllPostRequest.per_page', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=240,
)


_GETALLPOSTRESPONSE = _descriptor.Descriptor(
  name='GetAllPostResponse',
  full_name='GetAllPostResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='GetAllPostResponse.page', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='per_page', full_name='GetAllPostResponse.per_page', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='records', full_name='GetAllPostResponse.records', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=322,
)

_GETALLPOSTRESPONSE.fields_by_name['records'].message_type = _BLOGPOST
DESCRIPTOR.message_types_by_name['BlogPost'] = _BLOGPOST
DESCRIPTOR.message_types_by_name['CreateBlogPost'] = _CREATEBLOGPOST
DESCRIPTOR.message_types_by_name['GetPostRequest'] = _GETPOSTREQUEST
DESCRIPTOR.message_types_by_name['GetAllPostRequest'] = _GETALLPOSTREQUEST
DESCRIPTOR.message_types_by_name['GetAllPostResponse'] = _GETALLPOSTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlogPost = _reflection.GeneratedProtocolMessageType('BlogPost', (_message.Message,), {
  'DESCRIPTOR' : _BLOGPOST,
  '__module__' : 'blog_post_pb2'
  # @@protoc_insertion_point(class_scope:BlogPost)
  })
_sym_db.RegisterMessage(BlogPost)

CreateBlogPost = _reflection.GeneratedProtocolMessageType('CreateBlogPost', (_message.Message,), {
  'DESCRIPTOR' : _CREATEBLOGPOST,
  '__module__' : 'blog_post_pb2'
  # @@protoc_insertion_point(class_scope:CreateBlogPost)
  })
_sym_db.RegisterMessage(CreateBlogPost)

GetPostRequest = _reflection.GeneratedProtocolMessageType('GetPostRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPOSTREQUEST,
  '__module__' : 'blog_post_pb2'
  # @@protoc_insertion_point(class_scope:GetPostRequest)
  })
_sym_db.RegisterMessage(GetPostRequest)

GetAllPostRequest = _reflection.GeneratedProtocolMessageType('GetAllPostRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETALLPOSTREQUEST,
  '__module__' : 'blog_post_pb2'
  # @@protoc_insertion_point(class_scope:GetAllPostRequest)
  })
_sym_db.RegisterMessage(GetAllPostRequest)

GetAllPostResponse = _reflection.GeneratedProtocolMessageType('GetAllPostResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETALLPOSTRESPONSE,
  '__module__' : 'blog_post_pb2'
  # @@protoc_insertion_point(class_scope:GetAllPostResponse)
  })
_sym_db.RegisterMessage(GetAllPostResponse)



_BLOGPOSTER = _descriptor.ServiceDescriptor(
  name='BlogPoster',
  full_name='BlogPoster',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=325,
  serialized_end=479,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreatePost',
    full_name='BlogPoster.CreatePost',
    index=0,
    containing_service=None,
    input_type=_CREATEBLOGPOST,
    output_type=_BLOGPOST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPost',
    full_name='BlogPoster.GetPost',
    index=1,
    containing_service=None,
    input_type=_GETPOSTREQUEST,
    output_type=_BLOGPOST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllPost',
    full_name='BlogPoster.GetAllPost',
    index=2,
    containing_service=None,
    input_type=_GETALLPOSTREQUEST,
    output_type=_GETALLPOSTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLOGPOSTER)

DESCRIPTOR.services_by_name['BlogPoster'] = _BLOGPOSTER

# @@protoc_insertion_point(module_scope)
