apiVersion: v1
kind: Service
metadata:
  name: server-svc
spec:
  selector:
    app: server-app
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: python-client-svc
spec:
  selector:
    app: python-client-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - name: db-port
    protocol: "TCP"
    port: 5432
    targetPort: 5432
  selector:
    app: postgres-be
