FROM python:3.9

MAINTAINER public@vadymkhodak.com

COPY server /app/
COPY __init__.py /app/__init__.py
COPY blog_post_pb2.py /app/blog_post_pb2.py
COPY blog_post_pb2_grpc.py /app/blog_post_pb2_grpc.py
COPY requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

EXPOSE 50051

CMD ["python", "poster_server.py"]